####
#### MOVIES
####
# Show all movies
GET http://localhost:3000/api/movies/

# Show movie - add correct id
### 
GET http://localhost:3000/api/movies/5e03cb37a11aac253cfe0914

# Add movie
###
POST http://localhost:3000/api/movies/
Content-Type: application/json

{
	"title": "New Film",
	"desc": "Lorem iosum dolir sit amet...",
	"category": ["Drama", "Historical"],
	"duration": "170",
	"premiere": "2019.12.24",
	"director": ["John Doe"],
    "image": "https://loremflickr.com/g/320/240/"
}

# Edit movie - add correct id
###
PUT http://localhost:3000/api/movies/5e03cb37a11aac253cfe0914
Content-Type: application/json

{
	"title": "New Film 2",
	"desc": "Lorem iosum dolir sit amet...",
	"category": ["Drama", "Historical"],
	"duration": "170",
	"premiere": "2019.12.24",
	"director": ["John Doe"],
    "image": "https://loremflickr.com/g/320/240/"
}

# Remove movie - add correct id
###
DELETE http://localhost:3000/api/movies/5df3d1254650e9159014129a
####
#### ROOMS
####
# Show all rooms
GET http://localhost:3000/api/rooms/

# Show room - add correct id
### 
GET http://localhost:3000/api/rooms/5e060aac06b7a9197496115a/

# Add room
###
POST http://localhost:3000/api/rooms/
Content-Type: application/json

{
	"name": "R102",
	"desc": "Lorem iosum dolir sit amet...",
	"seatsAvailable": "80"
}

# Edit room - add correct id
###
PUT http://localhost:3000/api/rooms/5e064a734310614b10f9743d
Content-Type: application/json

{
	"name": "R102",
	"desc": "Lorem iosum dolir sit amet...",
	"seatsAvailable": "80"
}

# Remove room - add correct id
###
DELETE http://localhost:3000/api/rooms/5e064a734310614b10f9743d

###
### SEATS
###
# Show seats in room - add correct id
### 
GET http://localhost:3000/api/rooms/5e064aaa4310614b10f9743e/seats

# Add seats to room - add correct id
###
POST http://localhost:3000/api/rooms/5e064aaa4310614b10f9743e/seats
Content-Type: application/json

{
	"num": "36",
	"row": "ZD",
	"checked": "false"
}

# Edit seats - add correct id
###
PUT http://localhost:3000/api/rooms/5e064aaa4310614b10f9743e/seats/5e064abd4310614b10f9743f
Content-Type: application/json

{
	"num": "12",
	"row": "CD",
	"checked": "false"
}

# Remove seat - add correct id
###
DELETE http://localhost:3000/api/rooms/5e064aaa4310614b10f9743e/seats/5e064abd4310614b10f9743f
