const MOVIES_LIST_FETCH_REQUESTED = 'MOVIES_LIST_FETCH_REQUESTED';
const MOVIES_LIST_FETCH_SUCCEEDED = 'MOVIES_LIST_FETCH_SUCCEEDED';
const MOVIES_LIST_FETCH_FAILED = 'MOVIES_LIST_FETCH_FAILED';

export default {
  MOVIES_LIST_FETCH_REQUESTED,
  MOVIES_LIST_FETCH_SUCCEEDED,
  MOVIES_LIST_FETCH_FAILED,
};
