const MOVIES_LIST_FETCH_REQUESTED = 'MOVIES_LIST_FETCH_REQUESTED';
const MOVIES_LIST_FETCH_SUCCEEDED = 'MOVIES_LIST_FETCH_SUCCEEDED';
const MOVIES_LIST_FETCH_FAILED = 'MOVIES_LIST_FETCH_FAILED';

const SET_RESERVATION_ITEM = 'SET_RESERVATION_ITEM';
const SET_RESERVATION_SEATS = 'SET_RESERVATION_SEATS';
const RESERVATION_SEATS_FETCH_REQUESTED = 'RESERVATION_SEATS_FETCH_REQUESTED';
const RESERVATION_SEATS_FETCH_SUCCEEDED = 'RESERVATION_SEATS_FETCH_SUCCEEDED';
const RESERVATION_SEATS_FETCH_FAILED = 'RESERVATION_SEATS_FETCH_FAILED';

export default {
  MOVIES_LIST_FETCH_REQUESTED,
  MOVIES_LIST_FETCH_SUCCEEDED,
  MOVIES_LIST_FETCH_FAILED,

  SET_RESERVATION_ITEM,
  SET_RESERVATION_SEATS,
  RESERVATION_SEATS_FETCH_REQUESTED,
  RESERVATION_SEATS_FETCH_SUCCEEDED,
  RESERVATION_SEATS_FETCH_FAILED,
};
